remote_theme: Huxpro/huxpro.github.io

plugins:
  - jekyll-remote-theme

title: Ria Arora
SEOTitle: Ria Arora | Robotics & AI Research Engineer
description: Robotics & AI Research Engineer · UdeM / MILA
header-img: ""
email: riaarora333@gmail.com

permalink: /blog/:title/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
