theme: minima

title: Ria Arora
email: riaarora333@gmail.com
description: Robotics & AI Research Engineer · UdeM / MILA
url: "https://korra141.github.io"

github_username: korra141

header_pages: []

permalink: /blog/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
